server:
  port: 8300 #服务端口
spring:
  application:
    name:  app-configserver #指定服务名
  cloud:
    config:
      server:
#        native:
#          search-locations: classpath:/configsrc/
        git: #配置git仓库地址
          uri: https://gitee.com/250203726/myconfig.git #配置文件所在仓库
          username: 250203726@qq.com
          password: whz19930223
          search-paths:
            - config  #配置文件所在根目录
      label: master	#分支名称
eureka:
  client:
    serviceUrl:
      defaultZone: http://nbers:nbers@118.89.179.157:8100/eureka #当存在多个注册中心集群时，用逗号隔开
    ###因为该应用为服务提供者，是eureka的一个客户端，需要注册到注册中心
    register-with-eureka: true
    ###是否需要从eureka上检索服务
    fetch-registry: true
  instance:
    prefer-ip-address: true #将自己的ip地址注册到Eureka服务中
    ip-address: 127.0.0.1
    instance-id: ${spring.application.name}###${server.port}
logging:
  config: classpath:config/logback-spring.xml
